name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.7.x'
      - uses: gittools/actions/gitversion/execute@v0.9.13
        id: gitversion
      - if: steps.gitversion.outputs.preReleaseLabel != ''
        run: npm version --no-git-tag-version ${{steps.gitversion.outputs.nuGetVersion}}-${{steps.gitversion.outputs.shortSha}}
      - if: steps.gitversion.outputs.preReleaseLabel == ''
        run: npm version --no-git-tag-version ${{steps.gitversion.outputs.nuGetVersion}}

      # Build
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - run: npm run docs

      # Release
      - name: Create GitHub Release
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: actions/create-release@v1
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
        env:
          GITHUB_TOKEN: ${{github.token}}

      # Publish (release only)
      - name: Publish documentation
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{github.token}}
          force_orphan: true
          publish_dir: docs
          cname: typescript.typedrest.net
      - name: Connect to registry (npmjs.com)
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Publish packages (npmjs.com)
        if: steps.gitversion.outputs.preReleaseLabel == ''
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Publish
      - name: Connect to registry (GitHub)
        if: github.event_name == 'push'
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@typedrest'
      - name: Publish packages (GitHub)
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/renovate/')
        run: |
          sed -i 's|"typedrest"|"@typedrest/typedrest"|g' package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
